First version
TilloRudolf/events-collector pull request #2
Opened 2020-04-15 10:13 UTC by TilloRudolf

another pull request

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +    private EventsRepository repository;
так делать плохо, в больших системах есть вероятность, что может не подтянуться или потянуться неверный бин, лучше делать через private final поле и вайрдить конструктор

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +@RestController
следует использовать верзнеуровневый requestMapping для отделения логики. вдруг твое api расщирится и понадобится регистрировать не только ивенты, но еще что нибудь

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +    public List<Event> eventsForLastMinute() {
голую коллекцию отдавать не очень правильно. лучше иметь класс обертку, в которой уже отдавать данный лист, как поле. почитай rest style

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +        return "OK";
очень плохой и неинформативный ответ.

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +    @ResponseBody
открой аннотацию ```RestController``` и посмотри, что внутри у нее есть

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/model/Event.java
> +    @JsonSerialize
зачем?

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/model/Event.java
> +    @JsonSerialize
есть  @JsonCreator и  @JsonProperty, почитай про них

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/model/Event.java
> +    final String name;
почему поля не private

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/model/Event.java
> +    final String description;
кажется, здесь должны быть какие то валидации, я могу сюда войну и мир загрузить?

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/EventsRepository.java
> +    Map<Long, EventItem> map = new LinkedHashMap<>();
у тебя во первых должен быть ключом atomicLong, а во вторых сама мапа должна быть защищена от data racing. ConcurrentHashMap нужно использовать

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/EventsRepository.java
> +    public void putEvent(Event event) {
не хватает javadoc для всех публичных методов

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/EventsRepository.java
> +        EventItem item = new EventItem(event, nextEventId.incrementAndGet());
в чем смысл этого маппинга?

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/EventsRepository.java
> +    private final static Long MINUTE_MILLIS = 60 * 1000L;
перепутаны модификаторы. сначала static, затем final

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/EventsRepository.java
> +        map.forEach((id, item) -> {
какова алгоритмическая сложность этой операции?

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/EventsRepository.java
> +        map.forEach((id, item) -> {
а если в мапе будет миллион элементов? а если миллиард?

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/EventsRepository.java
> +            } else {
ну подумай, как это более по человечески написать. вермишель какая-то)

2020-04-15 10:34 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/EventsRepository.java
> +        idsForRemove.forEach(id -> map.remove(id));
алгоритм можно придумать и получше. ты ходишь по мапе, потом еще по листу. как-то очень не очень

2020-04-15 11:53 UTC, TilloRudolf commented on src/main/java/com/back/eventscollector/model/Event.java
> +    final String name;
исправил

2020-04-15 11:53 UTC, TilloRudolf commented on src/main/java/com/back/eventscollector/model/Event.java
> +    @JsonSerialize
использовал

2020-04-15 11:54 UTC, TilloRudolf commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +    @ResponseBody
убрал излишнюю анотацию

2020-04-15 11:54 UTC, TilloRudolf commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +        return "OK";
обернул и немного расширил ответ

2020-04-15 11:55 UTC, TilloRudolf commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +    public List<Event> eventsForLastMinute() {
сделал обёртку

2020-04-15 11:56 UTC, TilloRudolf commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +@RestController
не совсем понял что надо. необходимо развёрнутое пояснение

2020-04-15 11:56 UTC, TilloRudolf commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +    private EventsRepository repository;
сделал

2020-04-15 15:48 UTC, Kirilllko requested changes

2020-04-15 15:48 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +@RestController
у тебя маппинг будет выглядеть сейчас :8080/minute, /hour и тд. а надо, чтобы это было что-то типа events/minute

2020-04-15 15:48 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +    @Autowired
это убрать

2020-04-15 15:48 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +    public EventsController(EventsRepository repository) {
а вот здесь добавить. тебе идея разве не подсказывает?

2020-04-15 15:48 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsControllerResponse.java
> +    public String getMsg() {
над геттерами тоже стоит указывать jsonProperty, потому что может маппинг потеряться, если поле переназовешь

2020-04-15 15:48 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsControllerResponse.java
> +    private final String msg;
эти поля обязательные в ответе?

2020-04-15 15:48 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +    @RequestMapping(value = "/hour", method = RequestMethod.GET)
зачем ты поставил вместо getMapping устаревшую аннотацию? спиздил откуда то?)

2020-04-15 15:48 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +        return new EventsControllerResponse("SUCCESS", event.getName());
а если по какой то причине ивент не положился, тоже success отдавать будешь?

2020-04-15 15:48 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/model/Event.java
> +    private final Long timestampMillis;
из названия не понятно, что это такое

2020-04-15 15:48 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/model/EventsResponse.java
> +    public EventsResponse(
лучше не делать конструктор публичным.

2020-04-15 15:48 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/model/EventsResponse.java
> +    private final List<Event> events;
а если ничего в мапе не будет, то что отдашь?

2020-04-15 15:48 UTC, Kirilllko commented on src/test/java/com/back/eventscollector/repository/EventsRepositoryTest.java
> +    public void eventsForDay() {
не совсем правильно) для тебя день, для японца ночь. last24hours. и в основном коде тоже поправить надо

2020-04-15 15:48 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +        List<Event> events = repository.forMinute();
почему бы не формировать ответ напрямую в сервисе а контроллеру оставить только обращение в сервис?

2020-04-15 15:48 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/EventsRepository.java
> +    Map<Long, EventItem> map = new LinkedHashMap<>();
все таки я думаю, что стоит добавить модификатор доступа и сделать мапу бином

2020-04-15 15:48 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/EventsRepository.java
> +        List<Event> list = new ArrayList<>();
потенциально получается, что метод будет удалять старые значения только в момент , когда к нему обратятся с ивентами, а если никто обращаться не будет, а будет только класть? =)

2020-04-15 15:48 UTC, Kirilllko commented on src/test/java/com/back/eventscollector/repository/EventsRepositoryTest.java
> +class EventsRepositoryTest {
делаешь успехи) только здорово было бы, если бы ты поднял контекст приложения и честно отправил post запрос в свой сервис, чтобы убедиться и в корректности (де)сериализации, и в правильности маппингов, которые ты выбрал. это называется компонентный (интеграционный) тест

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +    @Operation(summary = "Return events", description = "return by one of [minute, hour, 24hours]", tags = {"event"})
лучше использовать @ApiOperation. более расширенный функционал

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +    @Operation(summary = "Return events", description = "return by one of [minute, hour, 24hours]", tags = {"event"})
эта аннтоация не deprecated?

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +            @ApiResponse(responseCode = "405", description = "typo in parameter \"range\", correct values [minute, hour, 24hours]. For example: ?range=hour"),
почему это не bad request, а 405? глупости

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +    @RequestMapping(value = "/period", method = RequestMethod.GET)
GetMapping

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +        if (isValidRange(range)) {
ой не. так делать неправильно. здесь должна быть только одна строчка без всяких ифов

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +        if (isValidRange(range)) {
почитай про ErrorHandling и ControllerAdvice, плюс ты не должен сам что-то валидировать в этих местах. за тебя это должен делать jsr (те валидации, которые ты написал в транспортных объектах)

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +        TimesEnum timeRange = TimesEnum.getByValue(range);
это можно валидацией сделать. не надо гоородить огород)

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +    @RequestMapping(value = "/event", method = RequestMethod.PUT)
PutMapping

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +    private final EventsRepository repository;
збс!

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +        TimesEnum timeRange = TimesEnum.getByValue(range);
ну так у тебя здесь npe же будет скорее всего, если null засунешь. или getByValue может принять null?

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/model/Event.java
> +    @NotNull
я бы сюда пихал @NotBlank (посмотри реализацию, чтобы понять, что делает), и тогда не придется писать min 1

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/model/Event.java
> +public class Event {
все так же нет javadoc никаких. вот вместо того, чтобы городить в контроллере какие-то штуки с парсингом event лучше сюда добавь аннотации ApiModel и ApiModelProperty (использование можешь найти на странице свагера)

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/model/EventItem.java
> +public class EventItem {
нет javadoc

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/model/EventsResponse.java
> +    public EventsResponse(
up

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/model/EventsResponse.java
> +    private final List<Event> events;
up

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/EventsRepository.java
> +    private final TimeRepository repository;
не многовато репозиториев?

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/EventsRepository.java
> +    private final TimeRepository repository;
в чем смысл этой абстракции?

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/EventsRepository.java
> +    public void putEvent(Event event) {
up

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/EventsRepository.java
> +        EventItem item = new EventItem(event, nextEventId.incrementAndGet());
up

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/TimeRepository.java
> +        node.getEvents().forEach((k, v) -> {
ебать. зачем так сложно? это задача на 20 минут, зашли и вышли)

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/swagger/OpenApiConfig.java
> +    private static final String DESCRIPTION = "Simple events collector service.";
судя по тому, что ты написал сверху, он же не симпл, он уже нахуй рили рили difficult=)

2020-04-20 20:07 UTC, Kirilllko commented on src/test/java/com/back/eventscollector/controller/HttpRequestsTest.java
> +        ResponseEntity<EventsResponse> forEntity = restTemplate.getForEntity("http://localhost:" + port + "/events/period?range=minute", EventsResponse.class);
чот я думаю, что рест темплейт в спринге можно просто завайрдить и он и так будет знать порт, на которм стартануло приложение. и так сложно объявлять не надо будет. но это чисто в рамках подумать, править не надо

2020-04-20 20:07 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/repository/TimeRepository.java
> +    private final List<TimeRepositoryNode> nodes;
а вся эта великолепная система будет работать в concurrency? сдается мне, что нет

2020-04-20 20:07 UTC, Kirilllko commented on src/test/java/com/back/eventscollector/controller/HttpRequestsTest.java
> +        ResponseEntity<EventsResponse> forEntity = restTemplate.getForEntity("http://localhost:" + port + "/events/period", EventsResponse.class);
напиши параллельный тест, в котором будешь сразу тысячу записей добавлять и проверь, добавились ли они все.

2020-04-29 17:24 UTC, Kirilllko requested changes

2020-04-29 17:24 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/configs/HazelcastProperties.java
> +@ConfigurationProperties(prefix = "hazelcast")
если ты используешь spring config, то можно и статику засунуть в настройки, configuration properties, прочитай и научись пользоваться

2020-04-29 17:24 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/configs/HazelcastProperties.java
> +    public final static String TOO_OLD = "not handled, was more than day ago";
public static final

2020-04-29 17:24 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/configs/HourEntryListener.java
> +        _24hoursEventsCollection = hazelcastInstance.getMap(_24_HOURS_COLLECTION);
ни разу такого именования переменных не видел

2020-04-29 17:24 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +@Tag(name = "events", description = "takes events and gets event count")
с точки зрения семантики английского языка правильнее написать  accepts и provides

2020-04-29 17:24 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsControllerAdvice.java
> +    @ExceptionHandler(value = {HttpMessageNotReadableException.class, TimeBreakingException.class})
что за TimeBreakingException? твое собственное?

2020-04-29 17:24 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsControllerAdvice.java
> +        ExceptionSerialize exception = new ExceptionSerialize(
кажется это мой класс =)

2020-04-29 17:24 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/exception/ExceptionSerialize.java
> +    private final String message;
это может быть потенциальным ответом сервиса. почему здесь нет swagger?

2020-04-29 17:24 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/model/Event.java
> +    @NotNull
?

2020-04-29 17:39 UTC, Kirilllko requested changes

2020-04-29 17:39 UTC, Kirilllko commented on build.gradle
> +processResources {
ты понимаешь, зачем это нужно?

2020-04-29 17:39 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/configs/CacheConfig.java
> +        final HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(new Config());
бессмысленный final на самом деле. если ты это взял у меня, то хоть бы посмотрел, зачем пихать final внутрь метода=)

2020-04-29 17:39 UTC, Kirilllko commented on build.gradle
> +targetCompatibility = '1.8'
уже 13 жаба есть, чо на старье пишешь?)

2020-04-29 17:39 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/configs/MinuteEntryListener.java
> +    @PostConstruct
зачем это нужно?)

2020-04-29 17:39 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +            @ApiResponse(responseCode = "400", description = "event isn't handled",
description неинформативный. если пришла ошибка, то понятно, что ивент и так не положился. нужно объянсить потенциальному пользователю, что под этой ошибкой подразумевается. у тебя подразумевается, что неверно составлено тело запроса

2020-04-29 17:39 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/exception/TimeBreakingException.java
> +public class TimeBreakingException extends RuntimeException {
ааа лол, спиздил мой экс и добавил свое сообщение)))

2020-04-29 17:39 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/model/Event.java
> +public class Event implements Serializable {
зачем здесь маркер serializable?

2020-04-29 17:39 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/service/EventServiceImpl.java
> +    public EventsCount getCount(String timeCollection) {
неправильно внутри сервиса использовать стринги при использовании switch, а если у тебя билиберда придет? нужно завести енам, а не в статике хранить

2020-04-29 17:39 UTC, Kirilllko commented on src/main/java/com/back/eventscollector/service/EventServiceImpl.java
> +        if (deltaTime < MILLIS_IN_MINUTE) {
подумай, как это можно более элегантно написать. возможно написать какой-нить компаратор, который будет выбирать мапу по функции и класть, а не ифами. это задание на подумать, необязательно, что что-то получится более правильное

2020-04-29 17:39 UTC, Kirilllko commented on src/test/java/com/back/eventscollector/service/EventServiceTest.java
> +        Event minuteEvent = new Event("name", "created 57 seconds before", System.currentTimeMillis() - (MILLIS_IN_MINUTE - 5 * 1000));
не увидел параллельных тестов.

2020-04-29 17:39 UTC, Kirilllko commented on src/test/resources/application.yml
> +hazelcast:
почитай про хазель и про его интеграцию со сприногом, ты должен понимать, что это за параметры такие)

2020-04-29 17:39 UTC, Kirilllko commented on src/test/java/com/back/eventscollector/controller/HttpRequestsTest.java
> +        assertThat(Objects.requireNonNull(Objects.requireNonNull(forEntity.getBody()).getResult())).isEqualTo(TOO_OLD);
вот такие вещи не очень хорошо писать, тебе нужно проверить, что результат верен, ты его заранее знаешь, не нужно 10 раз оборачивать в objects.require.., чтобы просто убрать желтизну из-за того, что тебе подсказывает идея. руководствуйся здравым смыслом, а не только лишь подсказками=) тест должен быть наглядным, а тут нагромождено что-то

2020-05-01 14:28 UTC, TilloRudolf commented on src/main/java/com/back/eventscollector/configs/HourEntryListener.java
> +        _24hoursEventsCollection = hazelcastInstance.getMap(_24_HOURS_COLLECTION);
переименовал

2020-05-01 14:30 UTC, TilloRudolf commented on src/test/java/com/back/eventscollector/service/EventServiceTest.java
> +        Event minuteEvent = new Event("name", "created 57 seconds before", System.currentTimeMillis() - (MILLIS_IN_MINUTE - 5 * 1000));
тест написал

2020-05-01 14:30 UTC, TilloRudolf commented on src/test/java/com/back/eventscollector/controller/HttpRequestsTest.java
> +        assertThat(Objects.requireNonNull(Objects.requireNonNull(forEntity.getBody()).getResult())).isEqualTo(TOO_OLD);
подправил

2020-05-01 14:40 UTC, TilloRudolf commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +@Tag(name = "events", description = "takes events and gets event count")
исправил

2020-05-01 14:40 UTC, TilloRudolf commented on src/main/java/com/back/eventscollector/controller/EventsController.java
> +            @ApiResponse(responseCode = "400", description = "event isn't handled",
исправил

2020-05-14 18:40 UTC, TilloRudolf commented on src/main/java/com/back/eventscollector/configs/HazelcastProperties.java
> +    public final static String TOO_OLD = "not handled, was more than day ago";
исправил

2020-05-21 15:03 UTC, merged